# alias
alias nz='nvim ~/.zshrc'
alias sz='source ~/.zshrc'

HISTFILE=$HOME/.zsh_history
HISTSIZE=500000
SAVEHIST=500000


setopt APPENDHISTORY
setopt BANG_HIST                 # Treat the '!' character specially during expansion.
setopt EXTENDED_HISTORY          # Write the history file in the ":start:elapsed;command" format.
setopt INC_APPEND_HISTORY        # Write to the history file immediately, not when the shell exits.
setopt SHARE_HISTORY             # Share history between all sessions.
setopt HIST_EXPIRE_DUPS_FIRST    # Expire duplicate entries first when trimming history.
setopt HIST_IGNORE_DUPS          # Don't record an entry that was just recorded again.
setopt HIST_IGNORE_ALL_DUPS      # Delete old recorded entry if new entry is a duplicate.
setopt HIST_FIND_NO_DUPS         # Do not display a line previously found.
setopt HIST_IGNORE_SPACE         # Don't record an entry starting with a space.
setopt HIST_SAVE_NO_DUPS         # Don't write duplicate entries in the history file.
setopt HIST_REDUCE_BLANKS        # Remove superfluous blanks before recording entry.
setopt HIST_VERIFY               # Don't execute immediately upon history expansion.
setopt HIST_BEEP                 # Beep when accessing nonexistent history.


ZPLUG_HOME=path/to/zplug/
ZSH_THEME_STYLE=ys
if [[ -f $ZPLUG_HOME/init.zsh ]] {
	source $ZPLUG_HOME/init.zsh
	zplug "plugins/git", depth:1, from:oh-my-zsh
	zplug "plugins/svn", depth:1, from:oh-my-zsh
        #zplug "plugins/vi-mode",   from:oh-my-zsh
	zplug "jeffreytse/zsh-vi-mode", depth:1
	zplug "plugins/extract", depth:1, from:oh-my-zsh
	zplug "plugins/themes", depth:1, from:oh-my-zsh
	zplug "themes/ys", depth:1, from:oh-my-zsh, as:theme, if:"[[ $ZSH_THEME_STYLE == ys ]]"
	zplug "themes/robbyrussell", depth:1, from:oh-my-zsh, as:theme, if:"[[ $ZSH_THEME_STYLE == robbyrussell ]]"
	zplug "zsh-users/zsh-syntax-highlighting", depth:1
	zplug "zsh-users/zsh-autosuggestions", depth:1
	zplug "zsh-users/zsh-history-substring-search", depth:1, on:"zsh-users/zsh-syntax-highlighting", defer:2
	zplug "MichaelAquilina/zsh-you-should-use", depth:1
	zplug "supercrabtree/k", depth:1
	zplug "zpm-zsh/ls", depth:1
	if ! zplug check --verbose; then
		echo 'Run "zplug install" to install'
	fi
	# Then, source plugins and add commands to $PATH
	zplug load
}

bindkey '`' autosuggest-accept

#bindkey -M vicmd 'k' history-substring-search-up
#bindkey -M vicmd 'j' history-substring-search-down


bindkey '^k' history-substring-search-up
bindkey '^j' history-substring-search-down
